apiVersion: v1
kind: Service
metadata:
  name: mysite-svc
  labels:
    class: cis-92-sp23
spec:
  type: LoadBalancer
  selector:
    function: webserver
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
