apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysite-deployment
  labels:
    app: django
spec:
  replicas: 2
  selector:
    matchLabels:
      app: django
  template:
    metadata:
      name: mysite-pod
      labels:
        app: django

    spec:
      containers:
      - name: httpd
        image: ghcr.io/mdella/cis-92-sp23:milestone-6.0
        resources:
          requests:
            cpu: 250m
            memory: 128Mi
          limits:
            cpu: 1000m 
            memory: 1Gi
            ephemeral-storage: 10Mi
        livenessProbe:
          httpGet:
            path: /polls
            port: 80
        ports:
        - containerPort: 80
        env:
        - name: PORT
          value: "80"
        - name: SECRET_KEY
          value: "blahblah"
        - name: DB_NAME
          value: "mysite"
        - name: DB_USER
          value: "postgres"
        - name: DB_PASSWORD
          value: "django"
        - name: DB_HOST
          value: "postgres"
