apiVersion: v1
kind: Pod
metadata:
  name: mysite-pod
  labels:
    function: webserver
    class: cis-92-sp23

spec:
  containers:
  - name: httpd
    image: ghcr.io/mdella/cis-92-sp23:milestone-4.3.2
    ports:
    - containerPort: 80
    env:
    - name: PORT
      value: "80"
    - name: SECRET_KEY
      value: "123abc"
