apiVersion: v1
kind: Pod
metadata:
  name: postgres
  labels:
    app: postgres
spec:
  volumes:
  - name: db
    persistentVolumeClaim:
        claimName: db
  containers:
  - name: postgres
    image: docker.io/postgres:14.1
    resources:
      requests:
        cpu: 500m
        memory: 256Mi
      limits:
        cpu: 1000m 
        memory: 1Gi
        ephemeral-storage: 10Mi
    ports:
    - containerPort: 5432
    volumeMounts:
    - name: db
      mountPath: /var/lib/postgresql
    env:
    - name: POSTGRES_PASSWORD
      value: "django"
    - name: POSTGRES_DB
      value: "mysite"
